name: Daily Paper Digest

on:
  schedule:
    # Run daily at 13:00 UTC (8 AM EST, 1 PM GMT)
    - cron: '0 13 * * *'
  workflow_dispatch: # Allow manual trigger

env:
  PYTHON_VERSION: '3.11'

jobs:
  send-digest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      working-directory: ./agent
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run PaperPulse Agent
      working-directory: ./agent
      env:
        # Email service configuration
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        FROM_NAME: "PaperPulse"
        
        # Supabase configuration
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        
        # Agent configuration
        MAX_PAPERS_PER_KEYWORD: 50
        DIGEST_OUTPUT_DIR: "../web/public/static/digests"
        
        # Logging
        LOG_LEVEL: INFO
        
      run: |
        python -m paperpulse.main
        
    - name: Upload digest artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: daily-digest-${{ github.run_number }}
        path: |
          web/public/static/digests/*.json
          agent/logs/*.log
        retention-days: 30
        
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Daily Digest Failed - ${new Date().toISOString().split('T')[0]}`,
            body: `The daily paper digest workflow failed on ${new Date().toISOString()}.\n\nWorkflow run: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
            labels: ['bug', 'automation']
          })

  # Optional: Deploy updated digests to web app
  deploy-digests:
    needs: send-digest
    runs-on: ubuntu-latest
    if: success()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      if: github.ref == 'refs/heads/main'
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./web
        scope: ${{ secrets.VERCEL_ORG_ID }}
